title: Applied Probability Days
subtitle: July 7-9, 2021
description: >- # this means to ignore newlines until "baseurl:"
  Applied Probability Days Virtual workshop 2021.
url: "http://appliedprobabilitydays.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  appliedprobabilitydays

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.22.0"

minimal_mistakes_skin: "default" # "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise 


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-T075BJNY28"
    anonymize_ip: false # default
